version: '3.8'

services:
  backend:
    image: app-tec-b
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - DATASOURCE_USERNAME=admin
      - DATASOURCE_PASSWORD=admin123
      - JWT_SECRET=mysecretkey
      - JWT_EXPIRATION=3600
    depends_on:
      - postgres

  frontend:
    image: app-tec-f
    ports:
      - "80:80"
    depends_on:
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

#example
